### ISSUE TITLE
HDOS/runelite not working (weird tzdb.dat location issue)

### ISSUE THREAD

**Issue by simcye** [Adamcake/Bolt#41]
Attempting to launch HDOS from launcher version 0.9.0, nothing happens, causes this error: (from .local/share/bolt-launcher/hdos/launcher.log )
EDIT: runelite also has this issue
launcher gui says successful

running bolt from AUR on archlinux
`export JAVA_HOME=/usr/lib/jvm/java-17-openjdk/bin/java`

console output: 
```
[B] Successfully spawned game process with pid 231210
args = []
home = /home/redacted/.local/share/bolt-launcher/hdos
```

```
Exception in thread "main" java.lang.Error: java.io.FileNotFoundException: /home/redacted/.local/share/bolt-launcher/java-proxy/lib/tzdb.dat (Not a directory)
        at sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:261)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.util.calendar.ZoneInfoFile.<clinit>(ZoneInfoFile.java:251)
        at sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:589)
        at java.util.TimeZone.getTimeZone(TimeZone.java:560)
        at java.util.TimeZone.setDefaultZone(TimeZone.java:666)
        at java.util.TimeZone.getDefaultRef(TimeZone.java:636)
        at java.util.TimeZone.getDefault(TimeZone.java:625)
        at java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:657)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:601)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:580)
        at _a._a._a._i.<init>(_i.java:4)
        at _a._a._a._h.<clinit>(_h.java:11)
        at _a._a._a._g._z._a(_z.java:11)
        at _a._a._a._g._z.main(_z.java:1)
        at hdos.Launcher.main(Launcher.java:11)
Caused by: java.io.FileNotFoundException: /home/redacted/.local/share/bolt-launcher/java-proxy/lib/tzdb.dat (Not a directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:255)
        ... 15 more
```

going to .local/share/bolt-launcher/java-proxy/lib shows it's linked to /usr/lib/jvm/java-17-openjdk/bin/java/lib/ (which doesn't exist and can't exist because the java binary is already there...)

**Comment by Adamcake** [comment]
JAVA_HOME should be `/usr/lib/jvm/java-17-openjdk`.

i.e., the Java binary is expected to be at $JAVA_HOME/bin/java

**Comment by simcye** [comment]
well that's what I get for not reading good. thanks
