### ISSUE TITLE
Issues with GPU and HDOS plugin

### ISSUE THREAD

**Issue by charlesalec** [Adamcake/Bolt#6]
Bolt worked perfectly for the first few months, all functionality was there.
For the past week I'm unable to enable the GPU or HD plugins, they instantly switch back to off. 

Where is the logfile located?

Thanks for the help!

**Comment by Adamcake** [comment]
> Where is the logfile located?

If you installed from flatpak, runelite's logs will be stored here:
`cd ~/.var/app/com.adamcake.Bolt/data/bolt-launcher/.runelite/logs`

if not flatpak, then try:
`cd $XDG_DATA_HOME/bolt-launcher/.runelite/logs`
and if that doesn't exist then it's here:
`cd ~/.local/share/bolt-launcher/.runelite/logs`

The plugin issue is unlikely to be related to Bolt, but I'd suggest keeping your graphics drivers up-to-date by updating your package manager and/or flatpak.

**Comment by Yggnar** [comment]
Hi, so I'm having this problem as well, specifically when running Runelite using Bolt. The plugins work fine on the normal Runelite appimage.

**Comment by Adamcake** [comment]
I don't know anything about how those plugins work, but they shouldn't be
affected by anything Bolt is doing, unless the flatpak sandbox I'd causing
an issue. I'd suggest digging out your log file and sending it to the
plugin developer.

**Comment by Yggnar** [comment]
So, I'm not sure if this is helpful, but this is what the crash gives me when I try to launch HDOS:

java.lang.RuntimeException: Exception while creating the OpenGL context
	at org.lwjgl.opengl.awt.AWTGLCanvas.beforeRender(AWTGLCanvas.java:81)
	at hdos.Lt.D(Lt.java:11)
	at hdos.Lt.i(Lt.java:3)
	at hdos.Main.main(Main.java:46)
Caused by: java.awt.AWTException: No supported framebuffer configurations found
	at org.lwjgl.opengl.awt.PlatformLinuxGLCanvas.create(PlatformLinuxGLCanvas.java:68)
	at org.lwjgl.opengl.awt.PlatformLinuxGLCanvas.create(PlatformLinuxGLCanvas.java:121)
	at org.lwjgl.opengl.awt.AWTGLCanvas.beforeRender(AWTGLCanvas.java:79)
	... 3 more

Based on that and the [FAQ](https://github.com/runelite/runelite/wiki/GPU-FAQ) on the Runelite GPU plugin, it looks like bolt is causing Runelite and HDOS to not be able to properly detect my OpenGL settings? As mentioned before these plugins seem to work fine on vanilla runelite. I'm using Linux Mint if that makes any difference.

**Comment by Adamcake** [comment]
The error suggests glXChooseFBConfig or eglChooseConfig is failing to find any configs that meet the requirements for your screen. I don't know why that would happen, it would be nothing to do with Bolt but I suppose might be related to flatpak.

**Comment by Yggnar** [comment]
Any suggestions on how I might go about further troubleshooting? I'm very new to Linux. I appreciate all your help so far, especially with making Bolt to begin with.

**Comment by Adamcake** [comment]
I assume you've already checked to make sure your system meets the requirements in the FAQ you linked. What GPU do you have, and are your graphics drivers up-to-date? Do a full update of everything in your package manager and flatpak to be on the safe side.

**Comment by Adamcake** [comment]
This looks like the same issue

https://github.com/flatpak/flatpak/issues/138

This could be an nvidia issue? Make sure you have any proprietary nvidia stuff installed correctly, or just save yourself the headache and switch to AMD. Nvidia is a constant uphill battle to get stuff working.

**Comment by charlesalec** [comment]
So I hadn't played in a while, and for the the issue simply fixed itself, but I'm noticing it's appearing again. The error is:

`2024-02-06 14:22:44 CET [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: unable to find a fb config
	at net.runelite.rlawt.AWTContext.createGLContext(Native Method)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:308)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
	at client.uz(client.java:2380)
	at client.bc(client.java)
	at by.za(by.java:403)
	at by.io(by.java)
	at by.run(by.java:7195)
	at java.base/java.lang.Thread.run(Thread.java:840)
`

What is 'fb config' here?

Thanks for your time and help!

**Comment by Adamcake** [comment]
It means framebuffer config, it's opengl terminology. The error means there are 0 supported graphics configurations for your screen. Most likely you have an nvidia card without all the proprietary nvidia stuff installed via your package manager and/or flatpak to make it work correctly. Look into nvidia packages or upgrade to AMD.

**Comment by charlesalec** [comment]
A couple reboots somehow fixed it.
I work in AI so my GPU setup is crucial, and I avoid messing with it as it can then cause all sorts of issues with CUDA which is too much of a hassle.

For anyone who is experincing this error: reboot. I think it's caused if you boot, sleep, and then try enable HD or GPU plugin. 
I know it's a hassle, but being on Linux is chosing life in hardmode anyway.

Thanks for the support
